name: mern-app
services:
  arangodb:
    image: arangodb:3.10
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=test123
    volumes:
      - arango_data:/var/lib/arangodb3
    networks:
      - mern-app

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_URL=http://arangodb:8529/
      - DB_NAME=chatapp
      - DB_USER=admin
      - DB_PASSWORD=test123
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mern-app
    depends_on:
      - arangodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - WDS_SOCKET_PORT=0
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mern-app
    depends_on:
      - api

  caddy:
    image: caddy:2-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - mern-app
    depends_on:
      - api
      - frontend

volumes:
  arango_data:
  caddy_data:
  caddy_config:

networks:
  mern-app:
    driver: bridge
